version: "3.8"

services:

  postgres:
    hostname: postgres
    image: postgres:14
    environment:
    - POSTGRES_USER=user
    - POSTGRES_DB=model_manager
    - POSTGRES_PASSWORD=password
    ports:
    - 5432
    networks:
    - model-manager

  server:
    hostname: server
    build:
      context: .
      dockerfile: ./build/server/Dockerfile
    command:
    - run
    - --config
    - /etc/config/config.yaml
    environment:
      DB_PASSWORD: password
    ports:
    - 8080:8080
    - 8081:8081
    - 8082:8082
    volumes:
    - ./configs/server:/etc/config
    depends_on:
    - postgres
    networks:
    - model-manager

  loader:
    hostname: loader
    build:
      context: .
      dockerfile: ./build/loader/Dockerfile
    command:
    - run
    - --config
    - /etc/config/config.yaml
    environment:
      DB_PASSWORD: password
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
    volumes:
    - ./configs/loader:/etc/config
    depends_on:
    - postgres
    - server
    networks:
    - model-manager

networks:
  model-manager:
