apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-manager-server.fullname" . }}
  labels:
    {{- include "model-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    workerServiceGrpcPort: {{ .Values.workerServiceGrpcPort }}
    objectStore:
      s3:
        pathPrefix: {{ .Values.objectStore.s3.pathPrefix }}
    database:
      host: {{ .Values.global.database.host }}
      port: {{ .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.global.database.username }}
      passwordEnvName: DB_PASSWORD
    auth:
      enable: {{ .Values.global.auth.enable }}
      rbacInternalServerAddr: {{ .Values.global.auth.rbacInternalServerAddr }}
