apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-manager-server.fullname" . }}
  labels:
    {{- include "model-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    objectStore:
      s3:
	pathPrefix: {{ .Values.objectStore.s3.pathPrefix }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.database.username }}
      passwordEnvName: {{ .Values.database.passwordEnvName }}
