objectStore:
  s3:
    endpointUrl:
    region:
    bucket:
    pathPrefix: models
    baseModelPathPrefix: base-models

awsSecret:
  name:
  accessKeyIdKey:
  secretAccessKeyKey:

huggingFaceSecret:
  name:
  apiKeyKey:

downloader:
  kind: s3
  s3:
    endpointUrl: https://s3.us-west-2.amazonaws.com
    region: us-west-2
    bucket: llm-operator-models
    pathPrefix: v1/base-models
  huggingFace:
    cacheDir:

baseModels:

modelLoadInterval: 1m
runOnce: false
skipDbUpdate: false

database:
  host:
  port: 5432
  database: model_manager
  username:
  passwordEnvName: DB_PASSWORD

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/model-manager-loader
  pullPolicy: IfNotPresent

version:
