global:
  database:
    host:
    port:
    username:
    passwordEnvName:

  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

baseModels:

modelLoadInterval: 1m
runOnce: false
skipDbUpdate: false

huggingFaceSecret:
  name:
  apiKeyKey:

downloader:
  kind: s3
  s3:
    endpointUrl: https://s3.us-west-2.amazonaws.com
    region: us-west-2
    bucket: llm-operator-models
    pathPrefix: v1/base-models
  huggingFace:
    cacheDir:

database:
  database: model_manager

objectStore:
  s3:
    pathPrefix: models
    baseModelPathPrefix: base-models

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/model-manager-loader
  pullPolicy: IfNotPresent

version:
