objectStore:
  s3:
    endpointUrl:
    bucket:
    pathPrefix: models
    baseModelPathPrefix: base-models

awsSecret:
  name:
  accessKeyIdKey:
  secretAccessKeyKey:

huggingFaceSecret:
  name:
  apiKeyKey:

downloader:
  huggingFace:
    cacheDir: /hugging-face-cache

baseModels:

modelLoadInterval: 1m

database:
  host:
  port: 5432
  database: model_manager
  username:
  passwordEnvName: DB_PASSWORD

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/model-manager
  pullPolicy: IfNotPresent

version:
