httpPort: 8080
grpcPort: 8081
workerServiceGrpcPort: 8082

objectStore:
  s3:
    pathPrefix: models

database:
  host: postgres
  port: 5432
  database: model_manager
  username: user
  passwordEnvName: DB_PASSWORD
