objectStore:
  s3:
    endpointUrl: http://minio:9000
    region: dummy
    bucket: llm-operator
    pathPrefix: models
    baseModelPathPrefix: base-models

downloader:
  kind: s3
  s3:
    endpointUrl: https://s3.us-west-2.amazonaws.com
    region: us-west-2
    bucket: llm-operator-models
    pathPrefix: v1/base-models

baseModels:
- google/gemma-2b

modelLoadInterval: 1m

database:
  host: postgres
  port: 5432
  database: model_manager
  username: user
  passwordEnvName: DB_PASSWORD
