objectStore:
  s3:
    endpointUrl: http://minio:9000
    region: dummy
    bucket: llmariner
    pathPrefix: models
    baseModelPathPrefix: base-models

downloader:
  kind: s3
  s3:
    endpointUrl: https://s3.us-west-2.amazonaws.com
    region: us-west-2
    bucket: llm-operator-models
    pathPrefix: v1/base-models

baseModels:
- google/gemma-2b-it-q4

modelLoadInterval: 1m

modelManagerWorkerServiceServerAddr: server:8082
