objectStore:
  s3:
    endpointUrl: http://minio:9000
    bucket: llm-operator
    pathPrefix: models
    baseModelPathPrefix: base-models

downloader:
  huggingFace:
    cacheDir: /hugging-face-cache

baseModels:
- google/gemma-2b

modelLoadInterval: 1m

database:
  host: postgres
  port: 5432
  database: model_manager
  username: user
  passwordEnvName: DB_PASSWORD
