global:
  database:
    host:
    port:
    username:

  databaseSecret:
    name:
    key:

  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable:
    rbacInternalServerAddr:

  workerServiceGrpcService:
    annotations:

  workerServiceIngress:
    create: false
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

httpPort: 8080
grpcPort: 8081
workerServiceGrpcPort: 8082

database:
  database: model_manager

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/model-manager-server
  pullPolicy: IfNotPresent

version:
