global:
  database:
    host:
    port:
    username:

  databaseSecret:
    name:
    key:

  ingress:
    ingressClassName:

  auth:
    enable:
    rbacInternalServerAddr:

httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8082

database:
  database: model_manager

objectStore:
  s3:
    pathPrefix: models

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/model-manager-server
  pullPolicy: IfNotPresent

version:
