httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8082

objectStore:
  s3:
    pathPrefix: models

database:
  host:
  port: 5432
  database: model_manager
  username:
  passwordEnvName: DB_PASSWORD

replicaCount: 1
image:
  repository: llm-operator/model-manager-server
  # TODO(kenji): Change this to IfNotPresent. Currently we set the pullPolicy
  # to Never as it is required to use a loaded image in a Kind cluster.
  pullPolicy: Never

ingress:
  ingressClassName:

version: latest
