apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-manager-loader.fullname" . }}
  labels:
    {{- include "model-manager-loader.labels" . | nindent 4 }}
data:
  config.yaml: |
    objectStore:
      s3:
        pathPrefix: {{ .Values.objectStore.s3.pathPrefix }}
        baseModelPathPrefix: {{ .Values.objectStore.s3.baseModelPathPrefix }}
    downloader:
      huggingFace:
        cacheDir: {{ .Values.downloader.huggingFace.cacheDir }}
    baseModels:
    {{- range .Values.baseModels }}
    - {{ . }}
    {{- end }}
    modelLoadInterval: {{ .Values.modelLoadInterval }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.database.username }}
      passwordEnvName: {{ .Values.database.passwordEnvName }}
