apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-manager-loader.fullname" . }}
  labels:
    {{- include "model-manager-loader.labels" . | nindent 4 }}
data:
  config.yaml: |
    objectStore:
      s3:
        endpointUrl: {{ .Values.objectStore.s3.endpointUrl }}
        region: {{ .Values.objectStore.s3.region }}
        bucket: {{ .Values.objectStore.s3.bucket }}
        pathPrefix: {{ .Values.objectStore.s3.pathPrefix }}
        baseModelPathPrefix: {{ .Values.objectStore.s3.baseModelPathPrefix }}
    downloader:
      kind: {{ .Values.downloader.kind }}
      s3:
        endpointUrl: {{ .Values.downloader.s3.endpointUrl }}
        region: {{ .Values.downloader.s3.region }}
        bucket: {{ .Values.downloader.s3.bucket }}
        pathPrefix: {{ .Values.downloader.s3.pathPrefix }}
      huggingFace:
        cacheDir: {{ .Values.downloader.huggingFace.cacheDir }}
    baseModels:
    {{- range .Values.baseModels }}
    - {{ . }}
    {{- end }}
    modelLoadInterval: {{ .Values.modelLoadInterval }}
    runOnce: {{ .Values.runOnce }}
    skipDbUpdate: {{ .Values.skipDbUpdate }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.database.username }}
      passwordEnvName: {{ .Values.database.passwordEnvName }}
