apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model-manager-loader.fullname" . }}
  labels:
    {{- include "model-manager-loader.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "model-manager-loader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "model-manager-loader.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: model-manager-loader
        image: "{{ .Values.image.repository }}:{{ .Values.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - run
        - --config
        - /etc/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        env:
        - name: {{ .Values.database.passwordEnvName }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.databaseSecret.name }}
              key: {{ .Values.databaseSecret.key }}
        {{- with .Values.awsSecret }}
        {{- if .name }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .accessKeyIdKey }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .secretAccessKeyKey }}
        {{- end }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "model-manager-loader.fullname" . }}
