{{- if .Values.persistentVolume.enabled -}}
{{- if not .Values.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "model-manager-loader.fullname" . }}
  labels:
    {{- include "model-manager-loader.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: "{{ .Values.persistentVolume.size }}"
  storageClassName: "{{ .Values.persistentVolume.storageClassName }}"
{{- if .Values.persistentVolume.volumeName }}
  volumeName: "{{ .Values.persistentVolume.volumeName }}"
{{- end -}}
{{- if .Values.persistentVolume.volumeBindingMode }}
  volumeBindingMode: "{{ .Values.persistentVolume.volumeBindingMode }}"
{{- end }}
{{- if .Values.persistentVolume.selector }}
  selector:
  {{- toYaml .Values.persistentVolume.selector | nindent 4 }}
{{- end -}}
{{- end -}}
{{- end -}}
