{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "model-manager-loader.serviceAccountName" . }}
  labels:
    {{- include "model-manager-loader.labels" . | nindent 4 }}
{{- end -}}
